### ISSUE TITLE
Issue with relative path move-to

### ISSUE THREAD

**Issue by andydotxyz** [srwiley/oksvg#16]
I noticed that in some cases the relative move-to 'm' command seems to be incorrect.
For example the svg flile at https://fonts.gstatic.com/s/i/materialicons/skip_previous/v4/24px.svg should be the mirror image of https://fonts.gstatic.com/s/i/materialicons/skip_next/v4/24px.svg but the arrow's middle point is offset on Y value for some reason.

I could not find a fix quickly or I would have submitted a PR, sorry.

**Comment by srwiley** [comment]
Good one. I think I got it. When the current cursor location was not at the start of the path and a close path, Z command, was called, the current location was not being updated to the start of the path. Should be OK now in the latest commit.

**Comment by andydotxyz** [comment]
Perfect, thanks
