### ISSUE TITLE
Rect with missing X or Y crashes

### ISSUE THREAD

**Issue by andydotxyz** [srwiley/oksvg#19]
If you have the content `<rect fill="none" height="24" width="24"/>` then it hits a ParseError on "" (empty string).
It should, however, default to 0.
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/rect

Stack is approximately:
```
fyne.io/fynedesk/vendor/github.com/srwiley/oksvg.parseFloat(0xc00390ff90, 0x5, 0x40, 0x4014000000000000, 0x0, 0x0)
	/home/andy/Code/Go/src/fyne.io/fynedesk/vendor/github.com/srwiley/oksvg/svgd.go:525 +0xbe
fyne.io/fynedesk/vendor/github.com/srwiley/oksvg.(*PathCursor).ReadFloat(0xc002a56f00, 0xc00390ff90, 0x5, 0x0, 0x0)
	/home/andy/Code/Go/src/fyne.io/fynedesk/vendor/github.com/srwiley/oksvg/svgp.go:104 +0x236
fyne.io/fynedesk/vendor/github.com/srwiley/oksvg.(*PathCursor).GetPoints(0xc002a56f00, 0xc00390ff90, 0x5, 0x1, 0x0)
	/home/andy/Code/Go/src/fyne.io/fynedesk/vendor/github.com/srwiley/oksvg/svgp.go:136 +0x235
fyne.io/fynedesk/vendor/github.com/srwiley/oksvg.(*PathCursor).addSeg(0xc002a56f00, 0xc00390ff8f, 0x6, 0x0, 0x0)
	/home/andy/Code/Go/src/fyne.io/fynedesk/vendor/github.com/srwiley/oksvg/svgp.go:165 +0x78
fyne.io/fynedesk/vendor/github.com/srwiley/oksvg.(*PathCursor).CompilePath(0xc002a56f00, 0xc00390fe40, 0x156, 0xc000096f18, 0x4629fc)
	/home/andy/Code/Go/src/fyne.io/fynedesk/vendor/github.com/srwiley/oksvg/svgp.go:384 +0x10c
```

**Comment by srwiley** [comment]
I cannot reproduce this one Andy. If I embed <rect height="24" width="24"/> then I get a 24x24 black rectangle in the upper right corner of the image, so it does look like x and y default to 0 in the absence of any declaration.

**Comment by srwiley** [comment]
That is if I remove the fill="none". Otherwise it does nothing.

**Comment by andydotxyz** [comment]
Thanks @srwiley I think I may have messed up something on my end with an SVG processor before it hits oksvg.
Apologies.

**Comment by srwiley** [comment]
No problem
*upper left corner* I think I'm a bit dyslexic.
