### ISSUE TITLE
Support for defs

### ISSUE THREAD

**Issue by Noofbiz** [srwiley/oksvg#9]
Hello, 

An svg I'm trying to parse uses the [defs](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/defs) tag. I was thinking it could grab the elements defined in defs and save them in the SvgIcon's Ids, like it does for gradients.

**Comment by srwiley** [comment]
Defs merged into master branch. Thanks Noofbiz for helping with oksvg!
